--UC1 Creation of addressbook databse
USE ADDRESS_BOOK;


--UC2 create table address book
CREATE TABLE ADDRESS_BOOK_TABLE
(
FIRSTNAME VARCHAR(20),
LASTNAME VARCHAR(20),
ADDRESS VARCHAR(20),
CITY VARCHAR(20),
STATE VARCHAR(20),
ZIP VARCHAR(20),
EMAIL VARCHAR(20),
);
SELECT * FROM ADDRESS_BOOK_TABLE;


--UC3 Insert values in addressbook
INSERT INTO ADDRESS_BOOK_TABLE VALUES('ASTHA','AGARWAL','PURDILPUR','KANPUR','UP','35423','astha@gmail.com');
INSERT INTO ADDRESS_BOOK_TABLE VALUES('RAM','AGARWAL','PURDILPUR','DELHI','UP','35423','ram@gmail.com');
INSERT INTO ADDRESS_BOOK_TABLE VALUES('SHYAM','AGARWAL','PURDILPUR','GORAKHPUR','UP','35423','shyam@gmail.com');


--UC4 Update value in addressbook
UPDATE ADDRESS_BOOK_TABLE SET ADDRESS='SWAROOP_NAGAR' WHERE FIRSTNAME='RAM';


--UC5 delete value in addressbook
DELETE ADDRESS_BOOK_TABLE WHERE FIRSTNAME='RAM';


--UC6 retrieve data from addressbook
SELECT * FROM ADDRESS_BOOK_TABLE WHERE CITY='KANPUR';
SELECT * FROM ADDRESS_BOOK_TABLE WHERE STATE='UP';


--UC7 count data by city or state	
SELECT COUNT(STATE) FROM ADDRESS_BOOK_TABLE WHERE STATE='UP';
SELECT COUNT(CITY)FROM ADDRESS_BOOK_TABLE WHERE CITY='DELHI';


--UC8 retrieve data in sorted order of person name
SELECT * FROM ADDRESS_BOOK_TABLE WHERE STATE='UP' ORDER BY FIRSTNAME;